version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_DSN=postgresql://user:password@postgres:5432/travelagent
    volumes:
      - ./backend:/app
    command: python3 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7
    container_name: travelagent_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15
    container_name: travelagent_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: travelagent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
